apiVersion: v1
kind: ConfigMap
metadata:
  name: my-garage-config
  namespace: my-garage
data:
  FRONTEND_URL: "https://my-garage.example.com"
  CORS_ORIGINS: "https://my-garage.example.com,http://localhost:4200"
