apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-garage-backend-media-pv
  labels:
    app.kubernetes.io/name: my-garage-backend-media
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.0.0.10
    path: /exports/my-garage/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-garage-backend-media
  namespace: my-garage
  labels:
    app.kubernetes.io/name: my-garage-backend-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-media
  volumeName: my-garage-backend-media-pv
