"""Separate vehicle specs into dedicated table

Revision ID: 02464d98749a
Revises: f71ab1610a3c
Create Date: 2025-11-22 01:11:16.446509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02464d98749a'
down_revision: Union[str, Sequence[str], None] = 'f71ab1610a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclespecs',
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engine_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engine_oil_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coolant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('battery_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tire_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('torque_specs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.drop_column('vehicle', 'vin')
    op.drop_column('vehicle', 'engine_type')
    op.drop_column('vehicle', 'battery_type')
    op.drop_column('vehicle', 'engine_oil_type')
    op.drop_column('vehicle', 'fuel_type')
    op.drop_column('vehicle', 'transmission')
    op.drop_column('vehicle', 'tire_size')
    op.drop_column('vehicle', 'coolant_type')
    op.drop_column('vehicle', 'color')
    op.drop_column('vehicle', 'torque_specs')
    op.drop_column('vehicle', 'color_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('color_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('torque_specs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('coolant_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('tire_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('transmission', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('fuel_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('engine_oil_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('battery_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('vehiclespecs')
    # ### end Alembic commands ###
