"""replace_image_url_with_binary

Revision ID: 50b4cf8a9cd2
Revises: c1bfc74f9cc0
Create Date: 2025-11-21 03:21:35.870792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b4cf8a9cd2'
down_revision: Union[str, Sequence[str], None] = 'c1bfc74f9cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_binary', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'image_binary')
    # ### end Alembic commands ###
