"""refactor_relationships

Revision ID: 66f88dd8b672
Revises: 02464d98749a
Create Date: 2025-11-22 01:56:28.567042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f88dd8b672'
down_revision: Union[str, Sequence[str], None] = '02464d98749a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('part', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'part', 'invoice', ['invoice_id'], ['id'])
    op.create_foreign_key(None, 'part', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part', type_='foreignkey')
    op.drop_constraint(None, 'part', type_='foreignkey')
    op.drop_column('part', 'invoice_id')
    op.drop_column('part', 'supplier_id')
    # ### end Alembic commands ###
