"""add_vehicle_fields

Revision ID: 6eb98815c5b4
Revises: 12141c726307
Create Date: 2025-11-20 17:22:01.806049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb98815c5b4'
down_revision: Union[str, Sequence[str], None] = '12141c726307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('next_itv_date', sa.Date(), nullable=True))
    op.add_column('vehicle', sa.Column('next_insurance_date', sa.Date(), nullable=True))
    op.add_column('vehicle', sa.Column('last_insurance_amount', sa.Float(), nullable=True))
    op.add_column('vehicle', sa.Column('next_road_tax_date', sa.Date(), nullable=True))
    op.add_column('vehicle', sa.Column('last_road_tax_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'last_road_tax_amount')
    op.drop_column('vehicle', 'next_road_tax_date')
    op.drop_column('vehicle', 'last_insurance_amount')
    op.drop_column('vehicle', 'next_insurance_date')
    op.drop_column('vehicle', 'next_itv_date')
    # ### end Alembic commands ###
