"""add_tax_amount_to_invoice

Revision ID: 76df812ae51d
Revises: 00de089e208f
Create Date: 2025-11-24 21:29:23.853720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76df812ae51d'
down_revision: Union[str, Sequence[str], None] = '00de089e208f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('tax_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'tax_amount')
    # ### end Alembic commands ###
