"""Add vehicle image binary

Revision ID: c1623111d729
Revises: e0e2318c9607
Create Date: 2025-11-21 21:36:49.045492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1623111d729'
down_revision: Union[str, Sequence[str], None] = 'e0e2318c9607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('image_binary', sa.LargeBinary(), nullable=True))
    op.drop_column('vehicle', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'image_binary')
    # ### end Alembic commands ###
