"""Add tax_id to supplier

Revision ID: ca7c8c4c3a96
Revises: add_usage_type_track_records
Create Date: 2025-11-24 00:13:43.145274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca7c8c4c3a96'
down_revision: Union[str, Sequence[str], None] = 'add_usage_type_track_records'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('googleauthtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_googleauthtoken_google_id'), 'googleauthtoken', ['google_id'], unique=True)
    op.add_column('invoice', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'))
    op.add_column('invoice', sa.Column('extracted_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('invoice', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.alter_column('invoice', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoice', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invoice', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoice', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('invoice_maintenance_id_fkey'), 'invoice', type_='foreignkey')
    op.create_foreign_key(None, 'invoice', 'vehicle', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'invoice', 'supplier', ['supplier_id'], ['id'])
    op.drop_column('invoice', 'maintenance_id')
    op.add_column('supplier', sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'tax_id')
    op.add_column('invoice', sa.Column('maintenance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_maintenance_id_fkey'), 'invoice', 'maintenance', ['maintenance_id'], ['id'])
    op.alter_column('invoice', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoice', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoice', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('invoice', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('invoice', 'supplier_id')
    op.drop_column('invoice', 'vehicle_id')
    op.drop_column('invoice', 'error_message')
    op.drop_column('invoice', 'extracted_data')
    op.drop_column('invoice', 'status')
    op.drop_column('invoice', 'file_name')
    op.drop_index(op.f('ix_googleauthtoken_google_id'), table_name='googleauthtoken')
    op.drop_table('googleauthtoken')
    # ### end Alembic commands ###
