"""Add Track model and update TrackRecord relationship

Revision ID: d122ed5bc1bf
Revises: e57ff9b4dd44
Create Date: 2025-11-26 13:23:38.518424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd122ed5bc1bf'
down_revision: Union[str, Sequence[str], None] = 'e57ff9b4dd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('length_meters', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_name'), 'track', ['name'], unique=True)
    op.add_column('trackrecord', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trackrecord', 'track', ['track_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackrecord', type_='foreignkey')
    op.drop_column('trackrecord', 'track_id')
    op.drop_index(op.f('ix_track_name'), table_name='track')
    op.drop_table('track')
    # ### end Alembic commands ###
