"""Add invoice processing and google auth

Revision ID: e4da74d610cb
Revises: ca7c8c4c3a96
Create Date: 2025-11-24 00:31:59.492927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4da74d610cb'
down_revision: Union[str, Sequence[str], None] = 'ca7c8c4c3a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
