"""add_missing_specs_fields

Revision ID: e57ff9b4dd44
Revises: ee2095014640
Create Date: 2025-11-26 07:07:37.746276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e57ff9b4dd44'
down_revision: Union[str, Sequence[str], None] = 'ee2095014640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiclespecs', sa.Column('horsepower', sa.Integer(), nullable=True))
    op.add_column('vehiclespecs', sa.Column('torque', sa.Integer(), nullable=True))
    op.add_column('vehiclespecs', sa.Column('drivetrain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehiclespecs', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiclespecs', 'weight')
    op.drop_column('vehiclespecs', 'drivetrain')
    op.drop_column('vehiclespecs', 'torque')
    op.drop_column('vehiclespecs', 'horsepower')
    # ### end Alembic commands ###
