"""Add group and organizer fields to track_record

Revision ID: ee2095014640
Revises: 76df812ae51d
Create Date: 2025-11-25 01:40:59.112650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2095014640'
down_revision: Union[str, Sequence[str], None] = '76df812ae51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackrecord', sa.Column('group', sa.String(), nullable=True))
    op.add_column('trackrecord', sa.Column('organizer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackrecord', 'organizer')
    op.drop_column('trackrecord', 'group')
    # ### end Alembic commands ###
