"""Add api keys to settings

Revision ID: f6e689ddb42d
Revises: ad89c3d45fe7
Create Date: 2025-11-28 00:27:10.601533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6e689ddb42d'
down_revision: Union[str, Sequence[str], None] = 'ad89c3d45fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('google_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('settings', sa.Column('gemini_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'gemini_api_key')
    op.drop_column('settings', 'google_client_id')
    # ### end Alembic commands ###
