"""Add vehicle technical specifications

Revision ID: f71ab1610a3c
Revises: c1623111d729
Create Date: 2025-11-22 01:00:12.344208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f71ab1610a3c'
down_revision: Union[str, Sequence[str], None] = 'c1623111d729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('engine_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('color_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('kilometers', sa.Integer(), nullable=True))
    op.add_column('vehicle', sa.Column('engine_oil_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('coolant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('battery_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('tire_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vehicle', sa.Column('torque_specs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'torque_specs')
    op.drop_column('vehicle', 'tire_size')
    op.drop_column('vehicle', 'battery_type')
    op.drop_column('vehicle', 'coolant_type')
    op.drop_column('vehicle', 'engine_oil_type')
    op.drop_column('vehicle', 'kilometers')
    op.drop_column('vehicle', 'color_code')
    op.drop_column('vehicle', 'color')
    op.drop_column('vehicle', 'transmission')
    op.drop_column('vehicle', 'fuel_type')
    op.drop_column('vehicle', 'engine_type')
    op.drop_column('vehicle', 'vin')
    # ### end Alembic commands ###
