"""Add image_url to Track model

Revision ID: ffe36452ca1e
Revises: d122ed5bc1bf
Create Date: 2025-11-26 13:37:07.762304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffe36452ca1e'
down_revision: Union[str, Sequence[str], None] = 'd122ed5bc1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'image_url')
    # ### end Alembic commands ###
